### PR TITLE
Made the license more open-source friendly, and added the article "Th…

### PR DESCRIPTION
**Pull request by dgramop**
…e" in front of software in a few places in order to make it fit with definitions.

I'm not a lawyer, this isn't legal advice.

Ideally, people should be allowed to change up your software and distribute it under a new name.
That prevents people from trying to make a malicious modification and spread it under your name.

### CODE REVIEW

**Comment by dgramop** [comment]
In fact, by the old license, simply forking the code is considered redistribution.

**Comment by dgramop** [comment]
@zachhuff386 What do you think?

**Comment by zachhuff386** [comment]
The license is intended to prevent distributing modifications including changing the name. I don't plan on changing this for now.

**Comment by InfernoZeus** [comment]
@zachhuff386 I'm interested in adding support for the CLI to import `tar` archives in the same way as is supported by the Electron GUI. From what I can understand of the current LICENSE, unfortunately, I'm not able to offer these changes to be merged back into mainline.

> Can modify source-code but cannot distribute modifications

This line in particular prevents me from pushing any changes to a public fork in order to raise a pull request. Any view on perhaps changing that purely to allow community contributions?

**Pull request closed without merging**
