### PR TITLE
Consider opening GitHub issues

### PR DESCRIPTION
**Pull request by szhu**
Hi there -- first I just want to say thank you for making a great app. The combination of being lightweight, reliable, free, and open source is amazing! Also, thank you for constantly updating it over at least the past few months.

I wanted to ask if you could consider enabling the "Issues" tab on GitHub? This project is something that I'd like to recommend to friends and colleagues, and having an active issues section is a good indicator that an open source project is healthy.

### CODE REVIEW

**Comment by dansch94** [comment]
I also have interest an opening the issue tab.
I have some Problems with the build from source on MacOS to use Wireguard:

`╰─➤  bash <(curl -s https://raw.githubusercontent.com/pritunl/pritunl-client-electron/master/tools/install_macos.sh)
Install Pritunl Client? [y/N] y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   144  100   144    0     0    208      0 --:--:-- --:--:-- --:--:--   208
100 12.8M    0 12.8M    0     0  3242k      0 --:--:--  0:00:04 --:--:-- 4712k
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> electron@1.7.5 postinstall /Users/username/pritunl-client-electron-1.0.1436.36/client/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pritunl@1.0.143-6.36 No description
npm WARN pritunl@1.0.143-6.36 No repository field.
npm WARN pritunl@1.0.143-6.36 No license field.

added 310 packages from 175 contributors and audited 1055 packages in 8.54s
found 28 vulnerabilities (17 moderate, 9 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
✔ Rebuild Complete
CANNOT RUN WITH NODE 12.13.0
Electron Packager requires Node 4.0 or above.`

There are some Problems with the Electron Packager: https://github.com/electron/electron-packager/issues/863

**Comment by szhu** [comment]
@dansch94, can you open up a new PR-issue for this? (You can do it the same way I did.) I feel like people might be subscribed to this thread, and I want to make sure they are not spammed.

**Comment by gaby64** [comment]
minimize to tray is missing, or should be the default behaviour when tray icon is set to on

**Comment by slawn** [comment]
> minimize to tray is missing, or should be the default behaviour when tray icon is set to on

totally agree. I'm using it on Win and there is now way to minimize it to tray? If I hit X - it closes and disconnects...

**Comment by slawn** [comment]
> minimize to tray is missing, or should be the default behaviour when tray icon is set to on

totally agree. I'm using it on Win and there is now way to minimize it to tray? If I hit X - it closes and disconnects...

**Comment by pschiffe** [comment]
Minimize to tray on win worked with older pritunl client versions, but it doesn't work with the latest one.

**Comment by kaipee** [comment]
+1 This project needs to have an issue tracker.

Currently the official installations instructions for Arch do not work as no `pritunl-client-electron` package is found in the repo

```sh
yay pritunl
8 aur/pritunl-git 10744.de3c11b-1 (+0 0.00) 
    Enterprise VPN Server
7 pritunl/pritunl-strongswan 5.8.4-1 (1.1 MiB 3.9 MiB) 
    Open Source IPsec Implementation
6 pritunl/pritunl-ssh-host 1.0.1674.4-1 (6.1 KiB 15.7 KiB) 
    Pritunl Zero SSH Host Client
5 pritunl/pritunl-ssh 1.0.1674.4-1 (6.8 KiB 26.9 KiB) 
    Pritunl Zero SSH Client
4 pritunl/pritunl-ndppd 0.2.5-1 (66.0 KiB 185.4 KiB) 
    NDP Proxy Daemon
3 pritunl/pritunl-link 1.0.1515.10-1 (5.3 MiB 27.9 MiB) 
    Enterprise VPN Link Server
2 pritunl/pritunl-client-gtk 1.0.1865.25-1 (224.1 KiB 1.1 MiB) 
    Pritunl OpenVPN Client
1 pritunl/pritunl-client-electron-numix-theme 1.0.2418.61-1 (3.3 KiB 1.9 KiB) (Installed)
    Pritunl OpenVPN Electron Client Numix Theme
```

**Comment by szhu** [comment]
Hi @zachhuff386, thanks for taking a look at this.

If possible, can you clarify what closing this PR means with respect to my original question? (Or, more generally, what do you recommend users do when they find a bug?) Getting a response to this would be much appreciated.

I've noticed that quite a few people have +1'd the question, and I'm sure they -- and future people coming across this conversation -- would appreciate an explicit response as well. Thank you in advance!

**Comment by kaipee** [comment]
@szhu I'd just like to put forward that I am rapidly losing faith in the Pritunl project. It seems to be developed and maintained by just 1 person, with no public visibility on issues or ability to feed back into the project.

Given what this is - a VPN solution, I'm starting to view the 'holds all the keys' and 'behind closed doors' aspects that are coming to light as dangerous.

**Comment by zachhuff386** [comment]
There is already a significant volume of support emails. With the GitHub issues open it leads to users sending both emails and opening issues on the GitHub repositories. Both of the issues mentioned in this thread have already been fixed.

**Pull request closed without merging**
